
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root1214
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: friendspractice_development
